version: '3.7'

services:
  arthur:
    build:
      context: services/arthur
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      - FLASK_ENV=development
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

      # Constant
      - BASE_URL=https://api.spotify.com/v1
      - MERLIN_BASE_URL=
      - AUTH_URL=https://accounts.spotify.com/authorize
      - API_TOKEN_URL=https://accounts.spotify.com/api/token

      # Your settings go here
      - REDIRECT_URI=http://localhost:5000/authentication
      - CLIENT_ID=cea865ce9fe248ba97362bb5b4776980
      - CLIENT_SECRET=bd813faa49cc4c869f8f4bdb1c15eab7

    depends_on:
      - postgres

  postgres:
    build:
      context: ./services/db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  lancelot:
    build:
      context: ./services/lancelot
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - arthur