version: '3.7'

services:
  arthur:
    build:
      context: services/arthur
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      - FLASK_ENV=development
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

      # Constant
      - BASE_URL=https://api.spotify.com/v1
      - MERLIN_BASE_URL=
      - AUTH_URL=https://accounts.spotify.com/authorize
      - API_TOKEN_URL=https://accounts.spotify.com/api/token

      # Your settings go here
      - REDIRECT_URI=http://localhost:5000/authentication
      - CLIENT_ID=369a6c4b828e4dda98c6a47e891d5b2f
      - CLIENT_SECRET=5be944b9cb9b4897849438c3f586f9e5

#    depends_on:
#      - postgres

#  postgres:
#    build:
#      context: ./services/db
#      dockerfile: Dockerfile
#    expose:
#      - 5432
#    environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
#
  lancelot:
    build:
      context: ./services/lancelot
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - arthur