apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: arthur
  name: arthur
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: arthur
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: arthur
    spec:
      containers:
      - env:
        - name: API_TOKEN_URL
          value: https://accounts.spotify.com/api/token
        - name: AUTH_URL
          value: https://accounts.spotify.com/authorize
        - name: BASE_URL
          value: https://api.spotify.com/v1
        - name: CLIENT_ID
          value: 369a6c4b828e4dda98c6a47e891d5b2f
        - name: CLIENT_SECRET
          value: 5be944b9cb9b4897849438c3f586f9e5
        - name: FLASK_ENV
          value: development
        - name: MERLIN_BASE_URL
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: POSTGRES_USER
          value: postgres
        - name: REDIRECT_URI
          value: http://localhost:5000/authentication
        image: gcr.io/aerobic-amphora-291504/arthur-api:1.1
        imagePullPolicy: ""
        name: arthur
        ports:
        - containerPort: 5000
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
