apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: lancelot
  name: lancelot
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: lancelot
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: lancelot
    spec:
      containers:
      - image: gcr.io/aerobic-amphora-291504/lancelot:1.2.5
        imagePullPolicy: ""
        name: lancelot
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
