apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: merlin
  name: merlin
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: merlin
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: merlin
    spec:
      containers:
      - image: gcr.io/aerobic-amphora-291504/merlin:1.0.0
        imagePullPolicy: ""
        name: merlin
        ports:
          - containerPort: 5005
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
